### ISSUE TITLE
Team Member - Insight Research - Develop Interview Script

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/nightingale#10]
## Background
Before conducting the interviews in #27, we need a script to go off of so that all of the data collected can be analyzed for similarities. 

We'll structure the interviews around [design challenge question](https://github.com/revelry-foundation/nightingale/issues/25) and schedule them through #9. 

## Write an interview Script
- [x] When I complete the interview script
- [x] Then I will have an
   - [x] Interview checklist
   - [x] Pre-interview preparation
   - [x] Introductions
   - [x] Warm-up / icebreaker
   - [x] Warm-up Questions
   - [x] Insight based topic questions based on customer category
   - [x] Wrap-up section
- [x] And I can add it to #27 for guidance

**Comment by thomasknoll** [comment]
I believe [this doc](https://docs.google.com/document/d/10rMaoEpOBYDD4t9U9E3LlObje8MgxfTIQRuWjruXGTQ/edit) from @jeremybrady is on this path.

**Comment by thomasknoll** [comment]
starting off this process in https://us02web.zoom.us/j/7496378450

**Comment by jeremybrady** [comment]
**Contact Tracing**
Discovery Contextual Inquiry

**Interview checklist**
Stakeholder and user interviews often progress through key moments: introductions lead to warm-up questions, which lead to topic-specific questions, activities, etc. This checklist outlines those key moments, and suggests things to do as you go through them. Revelry Staff, please see this Google Doc Template

**Pre-interview preparation**
*   Set aside 10 minutes before the interview begins to help your team intentionally transition to an inquiring mindset, to clarify with your colleagues their respective roles, to check any technologies on which the interview will rely, etc.

**Make sure to**
*   Remind your team of the purpose of the interview
*   Establish clear roles for anyone who will join (for example, moderators, observers, notetakers, etc.).
*   Confirm with teammates, especially remote ones, how they might ask questions during the interview (for example, in a Slack thread)
*   Do a tech check: confirm that screen sharing, recording, etc. works
*   To be used at facilitators discretion—receipt of a signed participant agreement ([example](https://docs.google.com/document/d/1iYeAvAwK7_t2Cez-QH-HdrDs1ANImaF3X5Qz0-T9gZs/edit?usp=sharing))
*   Double-check any links, files, etc. that participants will need to evaluate (i.e., ensure that your concept, wireframes, or prototypes are available for testing)

**Introductions**
Spend 5 minutes at the beginning of the interview to clarify with the participant the parameters of the interview, and to give them a chance to ask any logistics-related questions.

**Make sure to**
*   Thank the participant for their time
*   Introduce yourself, and anyone who is joining you
*   Explain the purpose of your research
*   Provide an overview of the shape of the interview, including any required logistics (for example, screen sharing)
*   Confirm the expected length of the interview
*   Confirm receipt, if needed, of a signed participant agreement
*   Explain
    *   How you’ll take notes (for example “TapeACall”, Zoom video recording etc.).
    *   How you’ll use any notes you take (for example, unattributed quotes)
*   Ask the participant if they have questions at this time
*   If the participant consents, turn on the recorder

**Warm-up / icebreaker**
Spend 5-10 minutes establishing the cadence for the interview as a conversation rather than a stilted back and forth. Help the participant feel comfortable, and focus on gaining important context for the body of the interview.

**Make sure to**
*   Be polite; you’re a guest in the participant’s world
*   Give the participant your full attention (You can signal this by making eye contact, asking follow up questions, etc. Be aware that taking notes, especially on a laptop, can distract from the conversation itself)
*   Ask open-ended questions that will give you relevant information and help you form a better understanding of who this person is
*   Understand the degree to which this person is comfortable talking about themselves and their work, and at what speed. Be mindful and respectful of anything the the participant is uncomfortable talking about
*   Give the participant time to respond; don’t be afraid of awkward pauses
*   Ask for a “tour”: note any organizations, tools, rituals, or processes that affect your participant’s perspective
*   Start broad (“So to start, could you tell us how you got into this line of work?” or “What’s a day in your work-life like?”), and then slowly direct the interview toward any planned activities (“Could you share your screen and show me how you do that?”) or topic-specific questions (“How often do you file TPS reports?”)

**Questions**
**Warm-Up **
*   So to start, could you tell us how you got into this line of work?
*   Can you tell me about your role at…?
*   What’s a day in your work-life like?

**Insight based topic questions**
**Epidemiologist**
*   What’s your relationship like with your community as an epidemiologist?
*   How do you currently go about informing others about engaging w/ contact tracing?
*   How much time do you typically spend on informing others?
*   Tell me about the last time you tried to inform someone on tools and information around the efficacy of contact tracing and or veracity of the information coming from trusted sources?
*   What do you like about your current role as both a scientist and filmmaker uncovering people's stories?
*   What is the biggest pain point related to contact tracing?
*   Why do you keep doing the work to try to inform others about the risks of COVID-19 and the need for contact tracing... Why is it important to you?
*   What type of work around this issue have you created to help you with this?
*   What’s the hardest part about getting the hardest hit communities to report and share their COVID-19 status?
*   What are you currently doing to make this reporting easier?
*   How does this impact other areas of your life / work?
*   What other contact tracing tools have you tried out?
*   Have you shared these other products or tools with others and with how many on average?
*   How did you hear about these other contact tracing tools?
*   What do you like or dislike about these other contact tracing tools?
*   Are you looking for a solution or alternative for existing contact tracing tools?

**Other Categories—see list here**
*   What’s your relationship like with [topic … e.g. money, fitness, etc] 
*   How do you currently go about [problem / task]?
*   How much time do you typically spend on [problem / task]? 
*   Tell me about the last time you tried to [problem / task]? 
*   What do you like about how you currently [problem / task]? 
*   What is the biggest pain point related to [problem / task]? 
*   Why do you keep doing [problem / task] … why is it important to you? 
*   What type of work arounds have you created to help you with this? What’s the hardest part about [problem / task]? 
*   What are you currently doing to make this [problem / task] easier? 
*   How does this [problem / task] impact other areas of your life / work? 
*   What other products or tools have you tried out? 
*   Have you paid for any of these other products or tools? 
*   How did you hear about these other products or tools?  
*   What do you like or dislike about these other products or tools? 
*   Are you looking for a solution or alternative for [problem / task]? 

**Wrap-up**
Spend 5 minutes thanking the participant, communicating any next steps, and giving the participant a chance to ask any questions they might have.

**Make sure to**
*   Thank the participant for their time and reiterate the value of their contributions
*   Ask the participant if there was anything they think we missed or that they would like to add
*   Ask if it would be okay to contact them again with any follow up questions
*   Provide any agreed-upon incentives
*   Turn off the recorder
*   If possible, ensure the participant that they will receive a copy of what you’ve found during the research (so they know what happened with the input they gave)
*   If desired, ask them who else you might talk to (fun fact: this is called snowball sampling)

**Post-interview activities**
Once the interview is complete, spend 15 minutes completing a post-interview debrief. Tend to any post-interview logistics.

**Make sure to**
*   If you’ve recorded the interview: Move any recordings from your Google Drive to the project folder
*   Engage the team in a post-interview debrief (example) to discuss surprises and reflect on what you heard
*   Consider updating the interview guide based on your interview
*   If you promised the participant any follow-up communications, identify who will send them and when
*   Optional: Update our [study contact list](https://docs.google.com/spreadsheets/d/1pkg82J_Lx45qy2x-xrEukeAi3o6t3_ORu_ejn89wcCc/edit?usp=sharing)

**Comment by Mcscott142** [comment]
Interview Script is created with all attributes and placed in #27 for people to reference when conducting the interviews. Closing this one.
