### ISSUE TITLE
Track A - Server - User Reported Location Schema and API

### ISSUE THREAD

**Issue by CurtisVonRubenhoff** [revelry-foundation/nightingale#24]
The first step to building out the api to ingest user location data to make our contract tracing work is to decide how we are storing the data in the database. I think ultimately this will be based on how we collect the data in the first place (Discussion on that happening in #5).  

I think the core database table should be structured something like this:
```
reported_locations
  lat
  long
  reported_covid_positive
  reported_covid_symptoms
  verified_covid_positive
  visit_duration_minutes
  visit_datetime
```

I'm assuming here that keeping track of user locations of those not infected will also help our hotspot calculation. We'll definitely need to know the ratio of people with symptoms/positive test results to those without in order to show a relative indication of how infected a particular location might be.

A concern I have is how we keep track of symptoms/positive test in these records. There's certainly a bigger conversation to be had about how we actually confirm this stuff, but I'm wondering how that would look in terms of data. Do we want to be able to go back an update and entry as verified?

I'm also open to suggestions of extra data points to take in or remove

As far as API Endpoints are concerned we'll probably need these ones, but any more suggestions are nice.

report_user_location
retrieve_reported_locations 
check_location_for_nearby_hotspots

**Comment by iamjoshfrank** [comment]
@CurtisVonRubenhoff - solid write-up. Thank you! Here's my feedback and I'm happy to hear pushback from others!

---

> I'm assuming here that keeping track of user locations of those not infected will also help our hotspot calculation. We'll definitely need to know the ratio of people with symptoms/positive test results to those without in order to show a relative indication of how infected a particular location might be.

We don't need location data to leave the phone from users that remain negative. Our assumption is this will help with building trust in the system (we only upload your location data after you've indicated you tested positive; and anonymously; and only in order to help keep those in your community more safe).

---

Re: hotspot calculation - this is something we don't have to do in this prototype week, but we can reach out to experts to understand what this might mean / how it might be calculated.

My assumption: **IF** we provide users with a notification or other message along the lines of "There's a XX% chance you came into contact with someone that tested positive for COVID at Y location" that it's mostly based on proximity and time (was I down the street or at the same coffeshop take-out stand? was I in the same office? does the time I spent there overlap significantly with the time the person(s) that tested positive spent there?)

---

As for database table structure, I don't think we need to store (nor had we planned to ask for) a user's `reported_covid_symptoms`. Only negative/positive status, unless there's a compelling case for trying to collect symptom info (that will be a hard sell).

Maybe I'm misunderstanding the point of this column in the table. Maybe it's there b/c it's anticipating a date as a response, as in "I first discovered symptoms on X date."

---

re: `verified_covid_positive`
"Verifying" a COVID-positive status is going to be tricky. We're likely not going to wade into the waters of uploading verified test results or other such things. Open to hearing more about what you're anticipating with that field.

---

`visit_duration_minutes` might need to be augmented by start / stop times so that we can calculate the possibility of overlapping location visits between users and provide a more accurate notification.

---

API endpoints - keep in mind that one of the principles / value propositions is that we're only collecting data at the server for those that opt-in to sharing their location data after indicating they have had a positive test.

**Comment by DejaTrudeaux** [comment]
i took `reported_covid_symptoms` to mean a person is experiencing covid symptoms but hasn't taken a test or gotten results yet, like this would be a boolean? if so i'd be afraid of hypochondriacs saying yes here and messing up the data.. 🤔 

jw the difference between `reported_covid_positive` and `verified_covid_positive` 

how would we calculate percentage of people present at a hotspot with positive test results without also getting location data for people who have negative test results? or maybe that's not something we're looking to calculate. i think we were talking about probability of running into someone with covid but i guess we don't have to share locations of people without it

**Comment by CurtisVonRubenhoff** [comment]
we made a decision and implemented a schema for the requests. since we're only storing positive locations, we don't need those boolean fields. Right now the schema looks like this

```
positive_locations
  location,
  when,
  json_blob
```

closing this out.
