### ISSUE TITLE
Spike: Discovery and Proposal of Interpreting Location Exposure into a Percentage

### ISSUE THREAD

**Issue by brittneybrown** [revelry-foundation/nightingale#43]
_this ticket is WIP, glad to hear feedback from folks in comments_

## Background
In this milestone, we're looking to interpret the overlap of locations visited and date/time with locations where a user has declared a `Positive` test result. The purpose of this ticket is to investigate and propose headlines which will support this milestone. 

### Resources
- [Project App Doc](https://docs.google.com/document/d/1Ob3Z_RxdGALPhl3V0XqQhLLYLYKKmMRXHf3fGT640rE/edit?usp=sharing)

**Comment by iamjoshfrank** [comment]
FYI, @jwietelman and the engineers had an ad hoc planning meeting this morning. Here's how they're dividing up the work, which overlaps Milestones [2](https://github.com/revelry-foundation/nightingale/milestone/2), [3](https://github.com/revelry-foundation/nightingale/milestone/3), and [4](https://github.com/revelry-foundation/nightingale/milestone/4).

Here's the general shape of what they're proposing, for the sake of time/shipping this first iteration on a Proof of Concept:

- Negative phone sends query with the user's anonymized locations to look for matches server-side.
- If there are matching positive location results, those are sent back to the negative phone in order to display the matches.
- _**The server does not store the negative user's locations; it only uses them in-the-moment to perform the query and return any matching positive location results based on radius and timeframe.**_

**Comment by brittneybrown** [comment]
finished using this as a notepad. closing
