### ISSUE TITLE
Notification Continue Stationary

### ISSUE THREAD

**Issue by DejaTrudeaux** [revelry-foundation/nightingale#81]
When logging into Testflight for the first time, I noticed some things that did not happen in the app when testing locally. One of those things is that I received a push notification that says, `Continue Stationary <lat, lng>`. I don't know how this could be useful for someone and actually was unable to find this in the code so I just wanted to make sure this is intentional, and remove it if not.

Screenshot:
![IMG_3745](https://user-images.githubusercontent.com/39891937/83893169-3abf7880-a715-11ea-9724-734e5dddeb4f.PNG)

**Comment by iamjoshfrank** [comment]
@DejaTrudeaux - similar comment to #80 that I just left. Very much not intentional. Very likely a standard background notification from the geolocation library.

Same answer as on #80, too - if you want to champion getting this ready to work, go for it. For now, pausing the `Write` effort. Dropping it below the onboarding permissions Issue, b/c we should probably tackle those first.

**Comment by DejaTrudeaux** [comment]
looks like this notification will only happen during development, as per this comment: https://github.com/transistorsoft/react-native-background-geolocation/issues/919#issuecomment-562594941

so im going to go ahead and close this and we can ignore it for now, unless we see it in prod as well
